datetime docs
tidepool-org/docs pull request #10
Opened 2017-06-02 18:24 UTC by jebeck

What it says on the tin. Hope these are useful! Already published to GH Pages, so if y'all want to edit them before merging, you should republish.

2017-06-08 15:49 UTC, darinkrauss commented
Why don't all three of you,  @gniezen, @krystophv, and @cbwebdevelopment, review and approve. Whoever approves last has to merge into master! ;)  (Unless, of course, there is anything that needs to be addressed before it can be approved.)

2017-06-16 14:44 UTC, gniezen requested changes
Well done @jebeck on writing a very entertaining tutorial (as much as it could be ;) ) on datetimes at Tidepool.

2017-06-16 14:44 UTC, gniezen commented on datetime/diabetes-data.md
> +[^b]: Just kidding! We haven't actually seen this one yet at Tidepool. But it's the *only one*. Yes. *Really.*
footnotes `^b` and `^c` should be moved to `falsehoods.md`

2017-06-21 10:45 UTC, jebeck commented on datetime/diabetes-data.md
> +[^b]: Just kidding! We haven't actually seen this one yet at Tidepool. But it's the *only one*. Yes. *Really.*
I can make this small change on this branch if @darinkrauss or whoever adds me to the docs repo as an external contributor. Or feel free to edit the branch yourselves 🙂

2017-06-21 13:12 UTC, cbwebdevelopment commented on datetime/diabetes-data.md
> +[^b]: Just kidding! We haven't actually seen this one yet at Tidepool. But it's the *only one*. Yes. *Really.*
Thanks, Jana.  I'll push these changes.  Nice job 👍

2017-06-21 13:23 UTC, clintonium-119 approved these changes
I've moved and published the 2 out-of-place footnotes as suggested in @gniezen's feedback.

LGTM

2017-06-27 16:35 UTC, krystophv approved these changes
LGTM 👍

2017-06-28 14:47 UTC, gniezen approved these changes

2017-06-28 14:54 UTC, merged